spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtdb
    username: postgres
    password: p1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 4f8d2a9e7c6b1f3d5e8a2c9f7b6d4a1c
  expiration: 86400000